framework:

  csrf_protection: true
  translator:
    fallbacks: ~
  default_locale: "en_gb"

  secret: "THISISSECRET"

  router:
    resource: "routes/routing.yml"
    strict_requirements: ~

  session:
    storage_id: session.storage.php_bridge
    handler_id: ~

  ide: sublime

  templating:
    engines: ['twig']

sensio_framework_extra:
  request: { converters: true }

twig:
  debug: "%kernel.debug%"
  strict_variables: "%kernel.debug%"

doctrine:
  dbal:
    default_connection:       default
    connections:
      default:
        driver: pdo_mysql

  orm:
    auto_generate_proxy_classes: "%kernel.debug%"
    default_entity_manager: default
    entity_managers:
      default:
        connection: default
        auto_mapping: true
        mappings:
          WF:
            type: annotation
            dir: /app/Uniwise/Doctrine/Entity
            prefix: Doctrine\Entity
            is_bundle: false

jms_di_extra:
  locations:
    all_bundles: false
    bundles: [ApiBundle]
    directories: [/app/Uniwise/Symfony/Service, /app/Uniwise/Doctrine]

fos_rest:
  serializer:
    serialize_null: true
  view:
    view_response_listener: 'force'
    formats:
      json: true
  body_listener:
    decoders:
      json: fos_rest.decoder.json
      xml: fos_rest.decoder.xml
  body_converter:
    enabled: true
  format_listener:
    rules:
      - { path: ^/, priorities: [ json ], fallback_format: json, prefer_extension: true }

services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Uniwise\Symfony\Service\:
    resource: '/app/Uniwise/Symfony/Service/*'
    public: true

  Uniwise\Symfony\Bundle\:
    resource: '/app/Uniwise/Symfony/Bundle/*'
    tags: ['controller.service_arguments']
    calls:
      - [setContainer, ["@service_container"]]
